# Generated by Django 4.1.1 on 2022-09-15 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumes',
            name='image',
            field=models.ImageField(default='static/images/images.png', upload_to='images/'),
        ),
    ]
