# Generated by Django 4.1.1 on 2022-09-15 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_resumes_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumes',
            name='pdf',
            field=models.FileField(default='static/images/no_pdf.png', upload_to='pdfs/'),
        ),
    ]
