# Generated by Django 4.1.1 on 2022-09-15 10:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_resumes_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumes',
            name='created_data',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
